### PR TITLE
Use common 1pass package for Atom feed generation, hash building and request authentication

### PR DESCRIPTION
**Pull request by benilovj**
This change moves Atom feed generation and 1Pass hash building to the `1pass-common` module.

To do:

- [x] test with a real WP installation

### CODE REVIEW

**Comment by benilovj** [comment]
This is ready for review and testing.

**Comment by benilovj** [comment]
I've also added 669a9b4 which removes more code that now lives in `1pass-common`.

**Comment by benilovj** [comment]
*bump*

**Comment by benilovj** [comment]
I tested this using a local WP against `demo` and found that the autoload was missing (fixed in 62dae05). Is `init.php` the right place to put the `require`?

I also added instructions to the `README` about running this plugin from GitHub (a333f93).

This is ready for another review and should be ready to merge.

**Comment by duncanjbrown** [comment]
Require is in the right place, but not idiomatic WP. Adding a commit to make it so. 

I will attempt to build a WP release off this branch. Will merge if successful.

**Pull request merged**
